---
version: '3'
services:
  java_deploy:
    build: ./java_deploy
    volumes:
      - ./java_deploy:/var/lib/jenkins/workspace/javaSemantic
    depends_on:
      - mysql_server
    container_name: java_deploy
    links:
      - "mysql_server:34.93.213.174"

  mysql_server:
    image: mysql:5.7
    restart: always
    container_name: java_database
    environment:
      MYSQL_DATABASE: 'semantic'
      MYSQL_ROOT_PASSWORD: 'GkdxhypD1iEPpNy2'
